version: '3.8'

services:
  fuel-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fuel-cost-calculator
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
    user: root

volumes:
  jenkins_home:
